name: publish

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  version-check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check module version
        uses: tarantool/actions/check-module-version@better0fdead/check-version-change-tar-version
        with:
          module-name: 'roles.metrics-export'
